version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    # env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=password1234
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    links: 
      - mysqldb
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

volumes: 
  db: